---
services:
  did:
    build:
      context: .
      dockerfile: ./docker_archlinux_user/Dockerfile
      args:
        USER_NAME: yasunori
        GROUP_NAME: yasunori
        PASSWD: yasunori
        SHELL_NAME: zsh
        PKGLIST_FILE: ./custom_pkglist.txt
    container_name: did
    environment:
      TZ: Asia/Tokyo
    tty: true
    volumes:
      - type: bind
        source: ./Public
        target: $HOME/Public
      - type: bind
        source: ./Project
        target: $HOME/Project
