---
services:
  did:
    image: ghcr.io/yasunori0418/did:latest
    container_name: did
    hostname: did
    tty: true
    volumes:
      - type: bind
        source: ./Public
        target: /root/Public
      - type: bind
        source: ./Project
        target: /root/src/Project
