---
services:
  did:
    build:
      context: .
      dockerfile: ./.docker/Dockerfile
    container_name: did
    hostname: did
    tty: true
    volumes:
      - type: bind
        source: ./Public
        target: /root/Public
      - type: bind
        source: ./Project
        target: /root/Project
