FROM debian:bookworm-slim

COPY --from=busybox:glibc /bin/busybox /bin/busybox

RUN apt-get update && \
    apt-get install -y \
        locales \
        ninja-build \
        gettext \
        cmake \
        curl \
        zsh \
        git \
        && \
    for cmd in $(busybox --list) ; \
        do echo "#!/usr/bin/env bash\nbusybox ${cmd} \$@" > /usr/local/bin/$cmd ; \
    done && \
    chmod +x /usr/local/bin/*
