name: Docker Image CI

on:
  create:
  schedule: # Start once a week at monday
    - cron: "0 0 * * 1"
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.LOGIN_PAT }}
      - name: Build docker image
        run: |
          docker build --rm=true --force-rm=true --no-cache=true --pull=true \
          --tag="ghcr.io/${GITHUB_ACTOR}/did:latest" .
      - name: Push docker image to ghcr.io
        run: docker push "ghcr.io/${GITHUB_ACTOR}/did:latest"
